export const PLAYER_MOVE = 'PLAYER_MOVE';
export const CREATE_TREE = 'CREATE_TREE';
export const CREATE_TREASURE = 'CREATE_TREASURE';
export const REMOVE_TREASURE = 'REMOVE_TREASURE';
export const GENERATE_TREASURES = 'GENERATE_TREASURES';
export const INCREASE_RESULT = 'INCREASE_RESULT';
